name: Testar Conexão Supabase

on:
  workflow_dispatch:  # Permite executar manualmente
  push:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *'  # Diariamente ao meio-dia (UTC)

jobs:
  test-connection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Instalar dependências
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Testar conexão com Supabase
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        python scripts/data_loader.py
    
    - name: Resultado
      if: success()
      run: echo "✅ Teste passou! Conexão com Supabase funcionando."
